const en = {
  heroTitle: 'Restore access securely', heroText: 'Request a private reset link and choose a new password.',
  requestTitle: 'Reset your password', requestSubtitle: 'Enter your organization ID and account email.',
  organizationId: 'Organization ID', email: 'Email', request: 'Send reset link', requesting: 'Sending…',
  sentTitle: 'Check your email', sent: 'If an account matches these details, reset instructions have been sent.',
  confirmTitle: 'Choose a new password', confirmSubtitle: 'Use at least 12 characters, including upper and lower case letters, a number, and a symbol.',
  password: 'New password', confirmPassword: 'Confirm new password', submit: 'Set new password', submitting: 'Saving…',
  successTitle: 'Password updated', success: 'Your new password is ready to use.', invalidTitle: 'Reset link unavailable',
  invalid: 'This reset link is invalid or has expired. Request a new one to continue.', retry: 'Request another link',
  backToLogin: 'Back to sign in', required: 'This field is required.', emailInvalid: 'Enter a valid email address.',
  organizationInvalid: 'Enter a valid organization UUID.', passwordInvalid: 'The password does not meet the security requirements.',
  passwordMismatch: 'The passwords do not match.', requestError: 'Could not send the request. Please try again.',
  confirmError: 'Could not update the password. Please try again.', language: 'Interface language',
} as const;

export const passwordResetResources = {
  en,
  ru: { ...en, heroTitle: 'Безопасное восстановление доступа', heroText: 'Запросите персональную ссылку и задайте новый пароль.', requestTitle: 'Восстановление пароля', requestSubtitle: 'Введите ID организации и почту учётной записи.', organizationId: 'ID организации', email: 'Электронная почта', request: 'Отправить ссылку', requesting: 'Отправка…', sentTitle: 'Проверьте почту', sent: 'Если учётная запись с такими данными существует, инструкции по восстановлению отправлены.', confirmTitle: 'Задайте новый пароль', confirmSubtitle: 'Используйте не менее 12 символов: строчные и заглавные буквы, цифру и специальный символ.', password: 'Новый пароль', confirmPassword: 'Повторите новый пароль', submit: 'Сохранить новый пароль', submitting: 'Сохранение…', successTitle: 'Пароль изменён', success: 'Теперь можно войти с новым паролем.', invalidTitle: 'Ссылка недоступна', invalid: 'Ссылка недействительна или истекла. Запросите новую, чтобы продолжить.', retry: 'Запросить новую ссылку', backToLogin: 'Вернуться ко входу', required: 'Заполните это поле.', emailInvalid: 'Введите корректный адрес почты.', organizationInvalid: 'Введите корректный UUID организации.', passwordInvalid: 'Пароль не соответствует требованиям безопасности.', passwordMismatch: 'Пароли не совпадают.', requestError: 'Не удалось отправить запрос. Попробуйте снова.', confirmError: 'Не удалось изменить пароль. Попробуйте снова.', language: 'Язык интерфейса' },
  kk: { ...en, heroTitle: 'Қолжетімділікті қауіпсіз қалпына келтіру', heroText: 'Жеке қалпына келтіру сілтемесін сұрап, жаңа құпиясөз орнатыңыз.', requestTitle: 'Құпиясөзді қалпына келтіру', requestSubtitle: 'Ұйым ID-сін және тіркелгі поштасын енгізіңіз.', organizationId: 'Ұйым ID', email: 'Электрондық пошта', request: 'Сілтемені жіберу', requesting: 'Жіберілуде…', sentTitle: 'Поштаңызды тексеріңіз', sent: 'Егер мұндай деректері бар тіркелгі болса, қалпына келтіру нұсқаулары жіберілді.', confirmTitle: 'Жаңа құпиясөз орнатыңыз', confirmSubtitle: 'Кемінде 12 таңба, бас және кіші әріп, сан және арнайы таңба қолданыңыз.', password: 'Жаңа құпиясөз', confirmPassword: 'Жаңа құпиясөзді қайталаңыз', submit: 'Жаңа құпиясөзді сақтау', submitting: 'Сақталуда…', successTitle: 'Құпиясөз өзгертілді', success: 'Енді жаңа құпиясөзбен кіруге болады.', invalidTitle: 'Сілтеме қолжетімсіз', invalid: 'Сілтеме жарамсыз немесе мерзімі өткен. Жаңасын сұраңыз.', retry: 'Жаңа сілтеме сұрау', backToLogin: 'Кіруге оралу', required: 'Бұл өрісті толтырыңыз.', emailInvalid: 'Дұрыс электрондық пошта мекенжайын енгізіңіз.', organizationInvalid: 'Ұйымның дұрыс UUID мәнін енгізіңіз.', passwordInvalid: 'Құпиясөз қауіпсіздік талаптарына сай емес.', passwordMismatch: 'Құпиясөздер сәйкес келмейді.', requestError: 'Сұрауды жіберу мүмкін болмады. Қайталап көріңіз.', confirmError: 'Құпиясөзді өзгерту мүмкін болмады. Қайталап көріңіз.', language: 'Интерфейс тілі' },
  zh: { ...en, heroTitle: '安全恢复访问权限', heroText: '申请专属重置链接并设置新密码。', requestTitle: '重置密码', requestSubtitle: '请输入组织 ID 和账户邮箱。', organizationId: '组织 ID', email: '电子邮箱', request: '发送重置链接', requesting: '正在发送…', sentTitle: '请检查邮箱', sent: '如果存在与这些信息匹配的账户，我们已发送重置说明。', confirmTitle: '设置新密码', confirmSubtitle: '请使用至少 12 个字符，包含大小写字母、数字和特殊符号。', password: '新密码', confirmPassword: '确认新密码', submit: '保存新密码', submitting: '正在保存…', successTitle: '密码已更新', success: '现在可以使用新密码登录。', invalidTitle: '重置链接不可用', invalid: '此重置链接无效或已过期。请申请新链接。', retry: '申请新链接', backToLogin: '返回登录', required: '此项为必填项。', emailInvalid: '请输入有效的电子邮箱。', organizationInvalid: '请输入有效的组织 UUID。', passwordInvalid: '密码不符合安全要求。', passwordMismatch: '两次输入的密码不一致。', requestError: '无法发送请求，请重试。', confirmError: '无法更新密码，请重试。', language: '界面语言' },
} as const;
