import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { Prisma } from '@prisma/client';
import { USER_ROLES } from '@lms/shared/constants/roles';

import { rolePolicies } from '../modules/auth/roles.js';

const GENERATED_NOTICE = '<!-- GENERATED by `pnpm docs:generate`. DO NOT EDIT. -->\n\n';
const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'options', 'head'] as const;
const API_PREFIX = '/api/v1';

function markdownTable(headers: string[], rows: string[][]): string {
  const escape = (value: string) => value.replaceAll('|', '\\|').replaceAll('\n', ' ');
  return [
    `| ${headers.join(' | ')} |`,
    `|${headers.map(() => '---').join('|')}|`,
    ...rows.map((row) => `| ${row.map(escape).join(' | ')} |`),
  ].join('\n');
}

function quoted(value: string): string {
  return `\`${value}\``;
}

function moduleName(value: unknown): string {
  if (typeof value === 'function') return value.name;
  if (value && typeof value === 'object' && 'module' in value) {
    const moduleValue = (value as { module?: unknown }).module;
    if (typeof moduleValue === 'function') return moduleValue.name;
  }
  throw new Error(`Unsupported AppModule import metadata: ${String(value)}`);
}

function apiTag(path: string, tags: unknown): string {
  if (Array.isArray(tags) && tags.every((tag) => typeof tag === 'string') && tags.length > 0) {
    return [...tags].sort().join(', ');
  }
  return path.replace(/^\/api\/v1\/?/, '').split('/')[0] || 'root';
}

async function generate(): Promise<void> {
  process.env['NODE_ENV'] ??= 'test';
  process.env['JWT_SECRET'] ??= 'docs-generation-jwt-secret-at-least-32-chars';
  process.env['DATABASE_URL'] ??= 'postgresql://docs:docs@127.0.0.1:5432/docs_generation';
  process.env['BACKGROUND_JOBS_RUN_WORKER'] = 'false';

  const [{ AppModule }, { createOpenApiDocument }] = await Promise.all([
    import('../app.module.js'),
    import('../openapi/swagger.js'),
  ]);

  const prismaRole = Prisma.dmmf.datamodel.enums.find((item) => item.name === 'UserRole');
  assert.ok(prismaRole, 'Prisma UserRole enum was not found');
  const prismaRoles = prismaRole.values.map((value) => value.name).sort();
  const sharedRoles = [...USER_ROLES].sort();
  assert.deepEqual(prismaRoles, sharedRoles, 'Prisma UserRole and shared USER_ROLES must contain the same roles');

  const policyRoles = new Set(Object.values(rolePolicies).flat());
  for (const role of policyRoles) {
    assert.ok(USER_ROLES.includes(role), `rolePolicies references unknown role: ${role}`);
  }

  const imports = Reflect.getMetadata('imports', AppModule) as unknown[] | undefined;
  assert.ok(Array.isArray(imports), 'AppModule imports metadata was not found');
  const moduleNames = imports.map(moduleName).sort();
  assert.equal(new Set(moduleNames).size, moduleNames.length, 'AppModule contains duplicate direct module imports');

  const app = await NestFactory.create(AppModule, { logger: false });
  let document;
  try {
    app.setGlobalPrefix('api/v1');
    document = createOpenApiDocument(app);
  } finally {
    await app.close();
  }

  const operations: Array<{ method: string; path: string; tag: string; auth: string }> = [];
  for (const [path, item] of Object.entries(document.paths)) {
    if (!item) continue;
    for (const method of HTTP_METHODS) {
      const operation = item[method];
      if (!operation) continue;
      operations.push({
        method: method.toUpperCase(),
        path,
        tag: apiTag(path, operation.tags),
        auth: Array.isArray(operation.security) && operation.security.length === 0 ? 'public' : 'bearer',
      });
    }
  }
  operations.sort((left, right) =>
    left.path.localeCompare(right.path) || HTTP_METHODS.indexOf(left.method.toLowerCase() as typeof HTTP_METHODS[number])
      - HTTP_METHODS.indexOf(right.method.toLowerCase() as typeof HTTP_METHODS[number]),
  );

  const outputDirectory = resolve(process.cwd(), 'docs/generated');
  await mkdir(outputDirectory, { recursive: true });

  const apiIndex = `${GENERATED_NOTICE}# Generated API index

Runtime authority: \`${API_PREFIX}/api-json\`. This committed file is only a compact method/path/tag/auth index; it is not a second OpenAPI/DTO contract.

${markdownTable(
    ['Method', 'Path', 'Tag', 'Auth'],
    operations.map((operation) => [
      quoted(operation.method),
      quoted(operation.path),
      quoted(operation.tag),
      quoted(operation.auth),
    ]),
)}
`;

  const rbacIndex = `${GENERATED_NOTICE}# Generated RBAC policy index

Permissions owner: \`apps/api/src/modules/auth/roles.ts\` (\`rolePolicies\`). Role existence is checked against shared \`USER_ROLES\` and Prisma \`UserRole\`.

## Roles

${markdownTable(
    ['Role', 'Shared', 'Prisma', 'Referenced by policy'],
    USER_ROLES.map((role) => [
      quoted(role),
      'yes',
      'yes',
      policyRoles.has(role) ? 'yes' : 'no',
    ]),
)}

## Policies

${markdownTable(
    ['Policy', 'Roles'],
    Object.entries(rolePolicies)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([policy, roles]) => [
        quoted(policy),
        roles.map(quoted).join(', '),
      ]),
)}
`;

  const modulesIndex = `${GENERATED_NOTICE}# Generated AppModule imports

Canonical owner: \`apps/api/src/app.module.ts\`.

${markdownTable(['Module'], moduleNames.map((name) => [quoted(name)]))}
`;

  const entityModels = Prisma.dmmf.datamodel.models.map((model) => model.name).sort();
  const entityEnums = Prisma.dmmf.datamodel.enums
    .map((item) => ({ name: item.name, values: item.values.map((value) => value.name) }))
    .sort((left, right) => left.name.localeCompare(right.name));

  const entitiesIndex = `${GENERATED_NOTICE}# Generated Prisma entity index

Canonical owner: \`apps/api/prisma/schema.prisma\` via Prisma DMMF.

## Models

${markdownTable(['Model'], entityModels.map((name) => [quoted(name)]))}

## Enums

${markdownTable(
    ['Enum', 'Values'],
    entityEnums.map((item) => [
      quoted(item.name),
      item.values.map(quoted).join(', '),
    ]),
)}
`;

  const files = {
    'API_INDEX.md': apiIndex,
    'RBAC.md': rbacIndex,
    'MODULES.md': modulesIndex,
    'ENTITIES.md': entitiesIndex,
  };

  for (const [name, content] of Object.entries(files)) {
    await writeFile(resolve(outputDirectory, name), content, 'utf8');
  }
}

await generate();
