module.exports = {
  extensionsToTreatAsEsm: ['.ts'],
  moduleNameMapper: {
    '^\\./auth\\.guard\\.js$': '<rootDir>/src/modules/auth/auth.guard.ts',
    '^\\./auth\\.schemas\\.js$': '<rootDir>/src/modules/auth/auth.schemas.ts',
    '^\\./auth\\.service\\.js$': '<rootDir>/src/modules/auth/auth.service.ts',
    '^\\./auth\\.tokens\\.js$': '<rootDir>/src/modules/auth/auth.tokens.ts',
    '^\\./passwords\\.js$': '<rootDir>/src/modules/auth/passwords.ts',
    '^\\./organization-scope\\.js$': '<rootDir>/src/modules/auth/organization-scope.ts',
    '^\\./organization-scope\\.guard\\.js$': '<rootDir>/src/modules/auth/organization-scope.guard.ts',
    '^\\./roles\\.js$': '<rootDir>/src/modules/auth/roles.ts',
    '^\\./roles\\.guard\\.js$': '<rootDir>/src/modules/auth/roles.guard.ts',
    '^\\./courses\\.schemas\\.js$': '<rootDir>/src/modules/courses/courses.schemas.ts',
    '^\\./courses\\.service\\.js$': '<rootDir>/src/modules/courses/courses.service.ts',
    '^\\./groups\\.schemas\\.js$': '<rootDir>/src/modules/groups/groups.schemas.ts',
    '^\\./groups\\.service\\.js$': '<rootDir>/src/modules/groups/groups.service.ts',
    '^\\./lessons\\.schemas\\.js$': '<rootDir>/src/modules/lessons/lessons.schemas.ts',
    '^\\./lessons\\.service\\.js$': '<rootDir>/src/modules/lessons/lessons.service.ts',
    '^\\./memberships\\.schemas\\.js$': '<rootDir>/src/modules/memberships/memberships.schemas.ts',
    '^\\./memberships\\.service\\.js$': '<rootDir>/src/modules/memberships/memberships.service.ts',
    '^\\./organizations\\.schemas\\.js$': '<rootDir>/src/modules/organizations/organizations.schemas.ts',
    '^\\./organizations\\.service\\.js$': '<rootDir>/src/modules/organizations/organizations.service.ts',
    '^\\./users\\.schemas\\.js$': '<rootDir>/src/modules/users/users.schemas.ts',
    '^\\./users\\.service\\.js$': '<rootDir>/src/modules/users/users.service.ts',
    '^\\.\\./auth/auth\\.guard\\.js$': '<rootDir>/src/modules/auth/auth.guard.ts',
    '^\\.\\./auth/auth\\.module\\.js$': '<rootDir>/src/modules/auth/auth.module.ts',
    '^\\.\\./auth/organization-scope\\.js$': '<rootDir>/src/modules/auth/organization-scope.ts',
    '^\\.\\./auth/organization-scope\\.guard\\.js$': '<rootDir>/src/modules/auth/organization-scope.guard.ts',
    '^\\.\\./auth/roles\\.js$': '<rootDir>/src/modules/auth/roles.ts',
    '^\\.\\./auth/roles\\.guard\\.js$': '<rootDir>/src/modules/auth/roles.guard.ts',
    '^\\.\\./\\.\\./database/prisma\\.service\\.js$': '<rootDir>/src/database/prisma.service.ts',
  },
  roots: ['<rootDir>/src'],
  testEnvironment: 'node',
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        tsconfig: '<rootDir>/tsconfig.json',
        useESM: true,
      },
    ],
  },
};
