const baseConfig = require('./jest.config.cjs');

module.exports = {
  ...baseConfig,
  testMatch: [
    '<rootDir>/src/integration/api.database-smoke.spec.ts',
    '<rootDir>/src/integration/checklist-snapshot.database.spec.ts',
    '<rootDir>/src/integration/checklist-session-domain.database.spec.ts',
    '<rootDir>/src/integration/checklist-session-lifecycle.database.spec.ts',
    '<rootDir>/src/integration/checklist-scoring-v1.database.spec.ts',
    '<rootDir>/src/integration/checklist-session-reminders.database.spec.ts',
    '<rootDir>/src/integration/checklist-session-admin-api.database.spec.ts',
    '<rootDir>/src/integration/checklist-session-recalculate.database.spec.ts',
    '<rootDir>/src/integration/checklist-session-idempotency.database.spec.ts',
    '<rootDir>/src/integration/checklist-manager-analytics.database.spec.ts',
    '<rootDir>/src/integration/checklist-evaluation-scales.database.spec.ts',
    '<rootDir>/src/integration/checklist-observation-sheet-builder.database.spec.ts',
    '<rootDir>/src/integration/checklist-session-feedback.database.spec.ts',
    '<rootDir>/src/integration/checklist-deadline.database.spec.ts',
    '<rootDir>/src/integration/reports-summary.database.spec.ts',
    '<rootDir>/src/integration/org-structure-foundation.database.spec.ts',
    '<rootDir>/src/integration/departments-tree.database.spec.ts',
    '<rootDir>/src/integration/department-memberships.database.spec.ts',
    '<rootDir>/src/integration/department-managers.database.spec.ts',
    '<rootDir>/src/integration/department-headcounts.database.spec.ts',
    '<rootDir>/src/integration/positions.database.spec.ts',
    '<rootDir>/src/integration/legacy-position-migration.database.spec.ts',
    '<rootDir>/src/integration/learning-targets.database.spec.ts',
    '<rootDir>/src/integration/organization-access-scope.database.spec.ts',
    '<rootDir>/src/integration/reporting-lines.database.spec.ts',
    '<rootDir>/src/integration/org-structure-admin.database.spec.ts',
    '<rootDir>/src/integration/org-external-references.database.spec.ts',
  ],
  testPathIgnorePatterns: [],
  testTimeout: 60_000,
};
