module.exports = {
  extensionsToTreatAsEsm: ['.ts'],
  moduleNameMapper: {
    '^\\./api-exception\\.filter\\.js$': '<rootDir>/src/common/filters/api-exception.filter.ts',
    '^\\.\\./common/filters/api-exception\\.filter\\.js$': '<rootDir>/src/common/filters/api-exception.filter.ts',
    '^\\.\\./api-response\\.js$': '<rootDir>/src/common/api-response.ts',
    '^\\./openapi\\.document\\.js$': '<rootDir>/src/modules/openapi/openapi.document.ts',
    '^\\.\\./modules/health/health\\.controller\\.js$': '<rootDir>/src/modules/health/health.controller.ts',
    '^\\.\\./modules/openapi/openapi\\.controller\\.js$': '<rootDir>/src/modules/openapi/openapi.controller.ts',
    '^\\./auth\\.guard\\.js$': '<rootDir>/src/modules/auth/auth.guard.ts',
    '^\\./auth\\.schemas\\.js$': '<rootDir>/src/modules/auth/auth.schemas.ts',
    '^\\./auth\\.service\\.js$': '<rootDir>/src/modules/auth/auth.service.ts',
    '^\\./auth\\.tokens\\.js$': '<rootDir>/src/modules/auth/auth.tokens.ts',
    '^\\./passwords\\.js$': '<rootDir>/src/modules/auth/passwords.ts',
    '^\\.\\./auth/passwords\\.js$': '<rootDir>/src/modules/auth/passwords.ts',
    '^\\./organization-scope\\.js$': '<rootDir>/src/modules/auth/organization-scope.ts',
    '^\\./organization-scope\\.guard\\.js$': '<rootDir>/src/modules/auth/organization-scope.guard.ts',
    '^\\./roles\\.js$': '<rootDir>/src/modules/auth/roles.ts',
    '^\\./roles\\.guard\\.js$': '<rootDir>/src/modules/auth/roles.guard.ts',
    '^\\./assignments\\.schemas\\.js$': '<rootDir>/src/modules/assignments/assignments.schemas.ts',
    '^\\./assignments\\.service\\.js$': '<rootDir>/src/modules/assignments/assignments.service.ts',
    '^\\./progress\\.schemas\\.js$': '<rootDir>/src/modules/progress/progress.schemas.ts',
    '^\\./progress\\.service\\.js$': '<rootDir>/src/modules/progress/progress.service.ts',
    '^\\./assessments\\.schemas\\.js$': '<rootDir>/src/modules/assessments/assessments.schemas.ts',
    '^\\./assessments\\.service\\.js$': '<rootDir>/src/modules/assessments/assessments.service.ts',
    '^\\./assessment-questions\\.schemas\\.js$': '<rootDir>/src/modules/assessment-questions/assessment-questions.schemas.ts',
    '^\\./assessment-questions\\.service\\.js$': '<rootDir>/src/modules/assessment-questions/assessment-questions.service.ts',
    '^\\./assessment-attempts\\.schemas\\.js$': '<rootDir>/src/modules/assessment-attempts/assessment-attempts.schemas.ts',
    '^\\./assessment-attempts\\.service\\.js$': '<rootDir>/src/modules/assessment-attempts/assessment-attempts.service.ts',
    '^\\./assessment-results\\.service\\.js$': '<rootDir>/src/modules/assessment-attempts/assessment-results.service.ts',
    '^\\./certificates\\.schemas\\.js$': '<rootDir>/src/modules/certificates/certificates.schemas.ts',
    '^\\./certificates\\.service\\.js$': '<rootDir>/src/modules/certificates/certificates.service.ts',
    '^\\./course-materials\\.schemas\\.js$': '<rootDir>/src/modules/course-materials/course-materials.schemas.ts',
    '^\\./course-materials\\.service\\.js$': '<rootDir>/src/modules/course-materials/course-materials.service.ts',
    '^\\./courses\\.schemas\\.js$': '<rootDir>/src/modules/courses/courses.schemas.ts',
    '^\\./courses\\.service\\.js$': '<rootDir>/src/modules/courses/courses.service.ts',
    '^\\./groups\\.schemas\\.js$': '<rootDir>/src/modules/groups/groups.schemas.ts',
    '^\\./groups\\.service\\.js$': '<rootDir>/src/modules/groups/groups.service.ts',
    '^\\./lessons\\.schemas\\.js$': '<rootDir>/src/modules/lessons/lessons.schemas.ts',
    '^\\./lessons\\.service\\.js$': '<rootDir>/src/modules/lessons/lessons.service.ts',
    '^\\./memberships\\.schemas\\.js$': '<rootDir>/src/modules/memberships/memberships.schemas.ts',
    '^\\./memberships\\.service\\.js$': '<rootDir>/src/modules/memberships/memberships.service.ts',
    '^\\./organizations\\.schemas\\.js$': '<rootDir>/src/modules/organizations/organizations.schemas.ts',
    '^\\./organizations\\.service\\.js$': '<rootDir>/src/modules/organizations/organizations.service.ts',
    '^\\./upload\\.service\\.js$': '<rootDir>/src/modules/upload/upload.service.ts',
    '^\\./users\\.schemas\\.js$': '<rootDir>/src/modules/users/users.schemas.ts',
    '^\\./users\\.service\\.js$': '<rootDir>/src/modules/users/users.service.ts',
    '^\\.\\./auth/auth\\.controller\\.js$': '<rootDir>/src/modules/auth/auth.controller.ts',
    '^\\.\\./auth/auth\\.guard\\.js$': '<rootDir>/src/modules/auth/auth.guard.ts',
    '^\\.\\./auth/auth\\.module\\.js$': '<rootDir>/src/modules/auth/auth.module.ts',
    '^\\.\\./auth/organization-scope\\.js$': '<rootDir>/src/modules/auth/organization-scope.ts',
    '^\\.\\./auth/organization-scope\\.guard\\.js$': '<rootDir>/src/modules/auth/organization-scope.guard.ts',
    '^\\.\\./auth/roles\\.js$': '<rootDir>/src/modules/auth/roles.ts',
    '^\\.\\./auth/roles\\.guard\\.js$': '<rootDir>/src/modules/auth/roles.guard.ts',
    '^\\.\\./\\.\\./config/env\\.js$': '<rootDir>/src/config/env.ts',
    '^\\.\\./\\.\\./database/prisma\\.service\\.js$': '<rootDir>/src/database/prisma.service.ts',
  },
  roots: ['<rootDir>/src'],
  testEnvironment: 'node',
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.spec.ts',
    '!src/**/*.d.ts',
    '!src/main.ts',
    '!src/**/*.module.ts',
  ],
  coverageProvider: 'v8',
  coverageThreshold: {
    global: {
      statements: 70,
      branches: 50,
      functions: 70,
      lines: 70,
    },
  },
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        tsconfig: '<rootDir>/tsconfig.json',
        useESM: true,
      },
    ],
  },
};
